<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<br>
<table>
    <tr>
        <th>User ID</th>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
    </tr>
    <?php foreach ($users as $user) { ?>
        <tr>
            <td><?= $user->getId() ?></td>
            <td><?= $user->getUserName() ?></td>
            <td><?= $user->getFirstName() ?></td>
            <td><?= $user->getLastName() ?></td>
            <td><?= $user->getEmail() ?></td>
        </tr>
    <?php } ?>
</table>
<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>
