<?php include "header.phtml" ?>
    <!---------- Body starts --------------->
    <form method="POST">
        <table>
            <tr>
                <td><label>Username</label></td>
                <td><label>
                        <input name="userName" id="inputUName" placeholder="Enter desired username" required> <img id="imgUName" src="" alt="" width="16px" height="16px" hidden/> <p id="pUName" hidden></p>
                    </label></td>
            </tr>
            <tr>
                <td><label>Password</label></td>
                <td><label>
                        <input type="password" name="password" id="inputPassword" placeholder="Enter password"  required> <img id="imgPassword" src="" alt="" width="16px" height="16px" hidden /> <p id="pPassword" hidden></p>
                    </label></td>
            </tr>
            <tr>
                <td><label>Re-enter Password</label></td>
                <td><label>
                        <input type="password" name="password2" id="inputPassword2" placeholder="Re-enter password"  required> <img id="imgPassword2" src="" alt="" width="16px" height="16px" hidden /> <p id="pPassword2" hidden></p>
                    </label></td>
            </tr>
            <tr>
                <td><label>First Name</label></td>
                <td><label>
                        <input name="firstName" placeholder="Enter your first name" required>
                    </label></td>
            </tr>
            <tr>
                <td><label>Last Name</label></td>
                <td><label>
                        <input name="lastName" placeholder="Enter your last name" required>
                    </label></td>
            </tr>
            <tr>
                <td><label>Email Address</label></td>
                <td><label>
                        <input name="email" placeholder="Enter your email address" required>
                    </label></td>
            </tr>

            <tr>
                <td></td>
                <td><button name="create" id="createButton" type="submit" class="btn btn-default" value="submit">Create</button></td>
            </tr>
        </table>
    </form>

    <br>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>