<?php include "header.phtml" ?>
<!---------- Body starts --------------->
    <div>
    <?php if (isset($_SESSION['userName'])) { ?>
        <h1>Welcome <?php echo $_SESSION['userName'] ?></h1>
    <?php } ?>
    </div>

    <div>
        <p  class="text-center">
            <h2><br>Tools For Everyone</h2>
            Browse a number of different tools through our browse page
            <br>You can even search for a specific tool through <br>our handy search page
        </p>
    </div>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>